version: "3.7"
services:
  mysql:
    image: mysql:5.7
    ports:
      - "3307:3306"
    restart: always
    volumes:
      - ./datos/mysql:/var/lib/mysql
    networks:
      - mysql-network
    command: --max_allowed_packet=300MB
    environment:
      MYSQL_ROOT_PASSWORD: c3c1t3.2o19
      MYSQL_DATABASE: sisec
      MYSQL_USER: certificados
      MYSQL_PASSWORD: c3c1t3.2o19

  certificados-backend:
    build:
      context: ../certificados-server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    volumes:
      - ./datos/sisec/:/home/sisec
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/sisec?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: certificados
      SPRING_DATASOURCE_PASSWORD: c3c1t3.2o19
    networks:
      - mysql-network
    logging:
      options:
        max-size: "10m"
        max-file: "3"
  control-escolar-backend:
    build:
      args:
        user: control-escolar
        uid: 1000
      context: ../control-escolar-backend
      dockerfile: Dockerfile
    image: control-escolar-backend
    container_name: control-escolar-backend
    depends_on:
      - mysql
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ../control-escolar-backend:/var/www
      - ../control-escolar-backend/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - mysql-network
  egresados-backend:
    build:
      args:
        user: egresado
        uid: 1000
      context: ../egresados-backend
      dockerfile: Dockerfile
    image: egresados-backend
    container_name: egresados-backend
    depends_on:
      - mysql
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ../egresados-backend:/var/www
    networks:
      - mysql-network
  certificados-frontend:
    build:
      context: ../certificados-client
      dockerfile: Dockerfile
    ports:
      - "4000:80"
    restart: always
  nginx:
    image: nginx:1.17-alpine
    container_name: control-escolar-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ../control-escolar-backend:/var/www/
      - ../control-escolar-backend/nginx:/etc/nginx/conf.d
    networks:
      - mysql-network

networks:
  mysql-network:
