 const states = [
  "Aguascalientes",
  "Baja California",
  "Baja California Sur",
  "Campeche",
  "Coahuila",
  "Colima",
  "Chiapas",
  "Chihuahua",
  "Ciudad de México",
  "Durango",
  "Guanajuato",
  "Guerrero",
  "Hidalgo",
  "Jalisco",
  "México",
  "Michoacán",
  "Morelos",
  "Nayarit",
  "Nuevo León",
  "Oaxaca",
  "Puebla",
  "Querétaro",
  "Quintana Roo",
  "San Luis Potosí",
  "Sinaloa",
  "Sonora",
  "Tabasco",
  "Tamaulipas",
  "Tlaxcala",
  "Veracruz",
  "Yucatán",
  "Zacatecas",
];
const opcionesExperiencia = ["Excelente", "Buena", "Regular", "Necesita Mejorar", "N/A"];
const rules = [
  {
    required: true,
    message: "¡Esta pregunta es requerida!",
  },
];
const rulesText= [
  {
    required: true,
    message: "¡Esta pregunta es requerida!",
    max: 150,
  },
];
export default {
  q1: {
    question: "¿En qué frecuencia usas tus conocimientos y habilidades que adquiriste en el Bachillerato?",
    name: "q1",
    options: ["Muy Frecuentemente", "Frecuente", "Poco Frecuente", "Rara Vez"],
    rules,
  },
  q2: {
    question: "¿Qué conocimientos técnicos consideras que te hicieron falta durante tu Bachillerato?",
    name: "q2",
    options: ["Matemáticas", "Ciencias", "Competencias relacionadas con tu carrera", "Investigación"],
    rules,
  },
  q3: {
    question: "¿Qué habilidades consideras que te hicieron falta durante tu Bachillerato?",
    name: "q3",
    options: ["Comunicación", "Trabajo en equipo", "Liderazgo"],
    rules,
  },

  q4: {
    question: "¿A qué actividad te incorporaras al egresar?",
    name: "q4",
    options: ["Estudios universitarios y/o superiores", "Trabajar", "Estudiar y Trabajar", "Otra/Aún no sé"],
    rules,
  },
  q5: {
    question: "¿Qué carrera deseas estudiar al egresar?",
    name: "q5",
    rules: rulesText,
  },
  q6: {
    question: "¿Es una carrera afín a tu bachillerato?",
    name: "q6",
    options: ["Si", "No", "No Aplica"],
    rules,
  },
  q7: {
    question: "¿Planeas emigrar de tu comunidad y/o Ciudad para estudiar?",
    name: "q7",
    options: ["Si", "No"],
    rules,
  },
  q8: {
    question: "¿Planeas emigrar de tu comunidad y/o Ciudad para trabajar?",
    name: "q8",
    options: ["Si", "No"],
    rules,
  },
  q9: {
    question: "¿Cuál de estas frases describe mejor tu interés en trabajar?",
    name: "q9",
    options: [
      "Buscaré un trabajo relacionado a la carrera que estoy estudiando",
      "Buscaré un trabajo aunque no esté relacionado con la carrera que estoy estudiando",
      "Me encuentro trabajando en algo relacionado con la carrera que estoy estudiando",
      "Me encuentro trabajando en algo no relacionado con la carrera que estoy estudiando",
    ],
    rules,
  },
  q10: {
    question: "¿Cuáles son las causas por las que planeas trabajar al concluir el Bachillerato?",
    name: "q10",
    options: [
      "Falta de interés por estudiar",
      "Por situaciones personales y familiares",
      "Embarazo / Maternidad / Paternidad",
      "Falta de recursos económicos",
      "Por ubicación geográfica",
    ],
    rules,
  },
  q11: {
    question: "¿Cuál es la razón por la cuál no te has decidido?",
    name: "q11",
    rules: rulesText,
  },
  q12: {
    question: "Servicios Escolares",
    name: "q12",
    options: opcionesExperiencia,
    rules,
  },
  q13: {
    question: "Laboratorios",
    name: "q13",
    options: opcionesExperiencia,
    rules,
  },
  q14: {
    question: "Talleres",
    name: "q14",
    options: opcionesExperiencia,
    rules,
  },
  q15: {
    question: "Vinculación",
    name: "q15",
    options: opcionesExperiencia,
    rules,
  },
  q16: {
    question: "Docentes",
    name: "q16",
    options: opcionesExperiencia,
    rules,
  },
  q17: {
    question: "Áreas recreativas y deportivas",
    name: "q17",
    options: opcionesExperiencia,
    rules,
  },
  q18: {
    question: "Personal administrativo",
    name: "q18",
    options: opcionesExperiencia,
    rules,
  },
  q19: {
    question: "Personal directivo",
    name: "q19",
    options: opcionesExperiencia,
    rules,
  },
  q20: {
    question: "Sanitarios",
    name: "q20",
    options: opcionesExperiencia,
    rules,
  },
  q21: {
    question: "Aulas",
    name: "q21",
    options: opcionesExperiencia,
    rules,
  },
  q22: {
    question: "Espacios para comer",
    name: "q22",
    options: opcionesExperiencia,
    rules,
  },
  q23: {
    question: "Eventos culturales",
    name: "q23",
    options: opcionesExperiencia,
    rules,
  },
  q24: {
    question: "Eventos deportivos",
    name: "q24",
    options: opcionesExperiencia,
    rules,
  },
  q25: {
    question: "Eventos tecnológicos",
    name: "q25",
    options: opcionesExperiencia,
    rules,
  },
  q26: {
    question: "Eventos de emprendimiento",
    name: "q26",
    options: opcionesExperiencia,
    rules,
  },
  q27: {
    question: "¿De tu experiencia en el plantel que fue lo que más te gusto?",
    name: "q27",
    rules: rulesText,
  },
  q28: {
    question: "¿De tu experiencia en el plantel que es lo que mejorarías?",
    name: "q28",
    rules: rulesText,
  },
/*
  q1: {
    question: "1. ¿En qué frecuencia usas tus conocimientos y habilidades que adquiriste en el Bachillerato?",
    name: "q1",
    options: ["Muy Frecuentemente", "Frecuente", "Poco Frecuente", "Rara Vez"],
    rules,
  },
  q2: {
    question: "2. ¿Qué conocimientos técnicos consideras que te hicieron falta durante tu Bachillerato?",
    name: "q2",
    options: ["Matemáticas", "Ciencias", "Competencias relacionadas con tu carrera", "Investigación"],
    rules,
  },
  q3: {
   question: "3. ¿Qué habilidades consideras que te hicieron falta durante tu Bachillerato?",
    name: "q3",
    options: ["Comunicación", "Trabajo en equipo", "Liderazgo"],
    rules,
   },
  q4: {
    question: "4. ¿Actividad a la que te estas dedicando?",
    name: "q4",
    options: ["Estudiar", "Trabajar", "Estudiar y Trabajar", "Otra"],
    rules,
   },
  q5: {
    question:
      "5. Nombre de la Institución donde estas estudiando actualmente: (Nota: Nombre completo sin abreviaturas)",
    name: "q5",
    rules: rulesText,
  },
  q00: {
    question: "ubicación de la Institución",
    name: "q00",
    options: ["Dentro del país", "Fuera del país"],
  },  
  q6: {
    question: "6. Estado de la ubicación de la Institución donde estas estudiando",
    options: states,
    name: "q6",
    rules,
  },
  q06: {
    question: "6. Escribe la ubicación de la Institución donde estas estudiando",
    name: "q6",
    rules: rulesText,
  },
  q7: {
    question: "7. ¿Qué tipo de Institución es?",
    name: "q7",
    options: ["Pública", "Privada"],
    rules,
  },
  q8: {
    question: "8. Nombre de la carrera en la que estas estudiando: (Nota: Nombre completo sin abreviaturas)",
    name: "q8",
    rules: rulesText,
  },
  q9: {
    question: "9. ¿La carrera que estas estudiando actualmente es afín a la que estudiaste en el Bachillerato?",
    name: "q9",
    options: ["Si", "No"],
    rules,
  },

  q10: {
    question: "10. Nombre de la empresa donde estás trabajando",
    name: "q10",
    rules: rulesText,
  },
  q11: {
    question: "11. Giro de la empresa: (Ejemplo: Automotriz, Servicios, Agropecuario, Industrial, Manufactura.)",
    name: "q11",
    rules: rulesText,
  },
  q12: {
    question: "12. ¿Cuál es tu puesto o la actividad principal que realizas en tu trabajo?",
    name: "q12",
    rules: rulesText,
  },
  q13: {
    question: "13. Esta actividad o puesto ¿tiene relación con la carrera que estudiaste en el bachillerato?",
    name: "q13",
    options: ["Si", "No"],
    rules,
  },
  q14: {
    question: "14. ¿Cuánto ganas aproximadamente mensualmente?",
    name: "q14",
    options: ["0-3000", "3001-6000", "6001-10000", "10001-más"],
    rules,
  },
  q15: {
    question: "15. ¿Cuáles son las causas por las que actualmente no estás estudiando o trabajando?",
    name: "q15",
    options: [
      "Falta de interés por estudiar",
      "No aprobé el examen de admisión ",
      "Realizare o estoy realizando Servicio Social",
      "Realizare o estoy realizando Prácticas Profesionales",
      "No cuento con mi título de bachillerato",
      "Por situaciones personales y familiares",
      "Embarazo/ Maternidad / Paternidad",
      "No encuentro trabajo",
      "Otra razón",
    ],
    rules,
  },
  q16: {
    question: "16. Otra razón",
    name: "q16",
    rules: [{ max: 80, message: "¡Respuesta muy larga!" }],
  },*/
};
